fluentd/lib/parser_viaq_host_audit/lib/viaq_host_audit.rb
fluentd/lib/parser_viaq_host_audit/test/parser_viaq_host_audit_test.rb

This PR:
* fixes the parsing of linux audit logs to no longer rely upon the ordinal position of the time entry
* https://issues.redhat.com/browse/LOG-2266
/assign @alanconway @syedriko

LOG-2266: fix parsing of audit logs to not depend upon position

---

.gitignore
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb

This PR:
* Updates the viaq data model to add a sequence number to address log entries where timestamp does not provide great enough resolution
* https://issues.redhat.com/browse/LOG-2099
cc @alanconway @vimalk78

LOG-2099: Add sequence number to log messages to fix entry order

---

.gitignore
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb

(cherry picked from commit 36fbd2d6a7eb03e239ccea995038bc0262adaf0c)
This PR:
* Updates the viaq data model to add a sequence number to address log entries where timestamp does not provide great enough resolution
* https://issues.redhat.com/browse/LOG-2291
* forward port of #8 
cc @alanconway @vimalk78

LOG-2291: Add sequence number to log messages to fix entry order

---

fluentd/Dockerfile
fluentd/origin-meta.yaml

This PR updates the Dockerfile to use public base images
/assign @alanconway 
cc @alanconway 
* https://issues.redhat.com/browse/LOG-2353

LOG-2353: Update base images to be public

---

fluentd/Dockerfile
fluentd/Dockerfile.in
fluentd/fluentd.source0001.patch

Corrected the fluentd patch file so that it is actually applied
/cc @alanconway 
- JIRA: https://issues.redhat.com/browse/LOG-2176

LOG-2176: corrections to the previous commit

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb

This PR:
* Updates the viaq plugin to actually call the method to add sequence number to log records
/assign @vimalk78 
* https://issues.redhat.com/browse/LOG-2291

LOG-2291: Fix plugin to add sequence number

---

fluentd/lib/fluent-plugin-collected/lib/fluent/plugin/in_collected_tail_monitor.rb
fluentd/lib/fluent-plugin-collected/test/plugin/test_in_collected_tail_monitor.rb

Metric labels were incorrectly set as a "labels" field in the metric, rather than at the top level.  Regression introduced in: dac3eff6c | [LOG-1722](https://issues.redhat.com/browse/LOG-1722): Update fluentd to 1.14.5
Undetected due to lack of tests to verify the published metric - unit test only validate the label set internally, it was being misapplied to the metric.
NEED NEW TEST: Not sure how to test this in a fluentd unit test - we need to verify the metrics being
published by the prometheus client. We could check in an e2e test in the CLO, but there should be a test here.

LOG-2220: Fluentd collector not setting labels from /var/log/pods paths

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_elasticsearch_index_name.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_elasticsearch_index_name.rb

This PR:
* fixes the viaq plugin to resolve an undefined method for configuring structured index type
cc @alanconway 
https://issues.redhat.com/browse/LOG-2213

LOG-2213: Fix structured index type for undefined method

---

fluentd/lib/fluent-plugin-collected/lib/fluent/plugin/in_collected_tail_monitor.rb
fluentd/lib/fluent-plugin-collected/test/plugin/test_in_collected_tail_monitor.rb

Updated the collector metrics to collect from either /var/log/pods or /var/log/containers.
The collector will follow whichever log files are selected by the tail plugin.

LOG-2462 fluentd collected metric to track /pods or /containers

---

fluentd/lib/fluent-plugin-viaq_data_model/Gemfile.lock
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_flatten_labels.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_flatten_labels.rb

This PR:
* adds flatten label logic to the Viaq plugin
* Allows for excluding labels from flattening logic
* https://issues.redhat.com/browse/LOG-2523

LOG-2523: Add flatten labels logic to Viaq plugin

---

fluentd/lib/fluent-plugin-collected/lib/fluent/plugin/in_collected_tail_monitor.rb

This PR:
* Removes path from collected log metrics to reduce pressure on prometheus server
* https://issues.redhat.com/browse/LOG-2682

LOG-2682: Remove path from collected metrics

---

fluentd/lib/fluent-plugin-remote_syslog/lib/fluent/plugin/out_remote_syslog.rb
fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender/ssl_context.rb
fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender/tcp_sender.rb

The remote_syslog plugin does not expose configuration knobs for client certificate, key or key passphrase. This PR adds them.
/cc @vimalk78 
- JIRA: https://issues.redhat.com/browse/LOG-2843

LOG-2843: tls.key and tls.cert not in fluentd real configuration when forwarding logs using syslog tls

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_log_level_normalizer.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_log_level_normalizer.rb

Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
Add new Fluentd Filter Plugin for extracting log level from structured field if exits and checking is it match with log level from root field. Replace log level from root field if not match or set to default value.
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2819

LOG-2819: Extract log level from structured if exist

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb

This PR:
* adds openshift.cluster_id if the proper environment variable is present
* https://issues.redhat.com/browse/LOG-3112

LOG-3112: Add openshift.cluster_id

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb

This PR:
* actually calls the function to set the cluster_id
* https://github.com/ViaQ/logging-fluentd/pull/46
* https://issues.redhat.com/browse/LOG-3112

LOG-3112: fix calling the function to set the clusterId

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_openshift.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_openshift.rb

This reverts commit 45de7d0018ae16f22af937143d099fb8e5fd1789.
Revert change that breaks CLO

Revert "LOG-3112: fix calling the function to set the clusterId"

---

fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/viaq_data_model_log_level_normalizer.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_filter_viaq_data_model.rb
fluentd/lib/fluent-plugin-viaq_data_model/test/test_viaq_data_model_log_level_normalizer.rb

Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
This PR: 
- move code for extracting structured level to the separate method, this is need to not broke exited behavior with log level normalization  
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-2819

LOG-2819: move code for extracting structured level to the separate method

---

fluentd/lib/remote_syslog_sender/lib/remote_syslog_sender/ssl_context.rb

In `ssl_context.rb`, If `verify_mode` is used, the function uses incorrect variable name `context`, whereas it should be `ssl_context`
This PR fixes it.
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- Github issue: 
- JIRA: https://issues.redhat.com/browse/LOG-3244

LOG-3244: Fix variable name in Syslog ssl_context.rb

---

fluentd/fluent-plugin-detect-exceptions.source0001.patch

This PR adds regex to matching some JS exception, where `Error` not ending with colon (`:`). 
For example: it should cover the case if JS Error fired without message. : 
`const error = new Error()
console.log(error.stack)`  
produce next trace:
```
Error
at <anonymous>:1:15
```
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3761

LOG-3761: Fix pattern of regex for JS client side multiline exception

---

fluentd/Gemfile.lock
fluentd/rh-manifest.txt
fluentd/vendored_gem_src/rack/CHANGELOG.md
fluentd/vendored_gem_src/rack/README.md
fluentd/vendored_gem_src/rack/lib/rack/multipart/parser.rb
fluentd/vendored_gem_src/rack/lib/rack/utils.rb
fluentd/vendored_gem_src/rack/lib/rack/version.rb
fluentd/vendored_gem_src/rack/rack.gemspec

This PR update rack version to the `3.0.4.2` to address fix `CVE 2023-27530` ([ruby-advisory-db/CVE-2023-27530](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rack/CVE-2023-27530.yml))
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3781

LOG-3781: Update rack to address fix CVE-2023-27530

---

Dockerfile.unit
Makefile
fluentd/Dockerfile
fluentd/Dockerfile.in
fluentd/Gemfile
fluentd/Gemfile.lock
fluentd/lib/fluent-plugin-remote-syslog/fluent-plugin-remote-syslog.gemspec
fluentd/lib/fluent-plugin-remote_syslog/fluent-plugin-remote_syslog.gemspec
fluentd/lib/fluent-plugin-remote_syslog/test/plugin/out_remote_syslog.rb
fluentd/lib/syslog_protocol/test/test_packet.rb
fluentd/origin-meta.yaml

This PR:
* Updates fluent image to use ruby 3.1 availble on ubi9.1
Note: journal log collection against rhel8 based nodes is broken in the upstream until the 9.2 image can be released
* https://issues.redhat.com/browse/LOG-3471
* https://issues.redhat.com/browse/LOG-3832
replaces https://github.com/ViaQ/logging-fluentd/pull/56

LOG-3471: Upgrade to ruby 3.1 on ubi9

---

Dockerfile.unit
fluentd/Dockerfile
fluentd/Dockerfile.in
fluentd/install-gems.sh
fluentd/origin-meta.yaml

This PR:
* updates to ruby v3.1
* updates base to ubi9
* removes use of jemalloc because of seg fault on ubi9
* https://issues.redhat.com/browse/LOG-3832

LOG-3832: update fluent 1.14.6 to use ruby-3.1 and ubi9

---

fluentd/Gemfile.lock
fluentd/rh-manifest.txt
fluentd/vendored_gem_src/rack/CHANGELOG.md
fluentd/vendored_gem_src/rack/lib/rack.rb
fluentd/vendored_gem_src/rack/lib/rack/constants.rb
fluentd/vendored_gem_src/rack/lib/rack/multipart.rb
fluentd/vendored_gem_src/rack/lib/rack/query_parser.rb
fluentd/vendored_gem_src/rack/lib/rack/request.rb
fluentd/vendored_gem_src/rack/lib/rack/version.rb
fluentd/vendored_gem_src/rack/rack.gemspec

Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
This PR update rack version to the `3.0.6.1` to address fix `CVE 2023-27539` ([ruby-advisory-db/CVE-2023-27539](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rack/CVE-2023-27539.yml))
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:https://issues.redhat.com/browse/LOG-3815

LOG-3815: Update rack to address fix CVE-2023-27539

---

fluentd/Gemfile.lock

This PR update `activesupport` and `activemodel` gems version to the `6.1.7.3` to address fix `CVE-2023-28120` ([ruby-advisory-db/CVE-2023-28120](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/activesupport/CVE-2023-28120.yml))
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-3816

LOG-3816: Update activesupport and activemodel gems to address fix CVE-2023-28120

---

fluentd/fluentd.source0001.patch

This PR patches fluentd in_tail and position file to resolve prematurely closing watches when inodes are reused and there are multiple entries with the same inode.
* https://issues.redhat.com/browse/LOG-3633
* https://issues.redhat.com/browse/LOG-3629
* https://issues.redhat.com/browse/LOG-3299
* Conf tested: https://gist.github.com/jcantrill/99d913f0def1b87719b402078e258a4c
* Harness: https://gist.github.com/jcantrill/4dafdf19ef3acea1e716fb4fdb787e9d
Created small volume to promote reuse of inodes based on:
```
As root (sudo -i)
```
My observations before patch:
```
loggers: 250        linesize: 512      watches 240-300; missing watches >30s+; missing messages; 1000+ pos entries
```
after:
```
loggers: 250        linesize; 512      missed watches ~7ss,watch hovers 250-300+; pos file max …
```

LOG-3633: fix fluentd position file closing watches on re-used inodes

---

fluentd/Gemfile.lock
fluentd/rh-manifest.txt
fluentd/vendored_gem_src/rack/CHANGELOG.md
fluentd/vendored_gem_src/rack/lib/rack.rb
fluentd/vendored_gem_src/rack/lib/rack/constants.rb
fluentd/vendored_gem_src/rack/lib/rack/multipart.rb
fluentd/vendored_gem_src/rack/lib/rack/query_parser.rb
fluentd/vendored_gem_src/rack/lib/rack/request.rb
fluentd/vendored_gem_src/rack/lib/rack/version.rb
fluentd/vendored_gem_src/rack/rack.gemspec

Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
This PR update rack version to the `3.0.6.1` to address fix `CVE 2023-27539` ([ruby-advisory-db/CVE-2023-27539](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rack/CVE-2023-27539.yml))
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA:[issues.redhat.com/browse/LOG-3815](https://issues.redhat.com/browse/LOG-3815)

[release-5.7]LOG-3815: Update rack to address fix CVE-2023-27539

---

fluentd/fluentd.source0001.patch

Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
This PR fix a possible crash on file rotation when `follow_inodes` is  `true` by adds patch file based on changes introduced in https://github.com/fluent/fluentd/pull/3754
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4151

LOG-4151: add patch for: Fluentd fix missing nil check for rotated_tw in update_watcher

---

fluentd/Dockerfile
fluentd/fluentd.source0001.patch

This PR fix a possible crash on file rotation when `follow_inodes` is  `true` by adds patch file based on changes introduced in https://github.com/fluent/fluentd/pull/3754
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4150

LOG-4150: add patch for: Fluentd fix missing nil check for rotated_tw in update_watcher

---

fluentd/fluentd.source0001.patch

This PR:
* patches the way fluent uses inodes refs in a postition file
forward port of https://github.com/ViaQ/logging-fluentd/pull/83
https://issues.redhat.com/browse/LOG-4149

LOG-4149: fix fluentd position file closing watches on re-used inodes

---

fluentd/Gemfile
fluentd/Gemfile.lock

This PR:
* updates  fluent-plugin-splunk-hec to v1.3.2 to force the upgrade of activesupport gem to 7.0.6
* https://issues.redhat.com/browse/LOG-4316

LOG-4316: Update fluent-plugin-splunk-hec to v1.3.2

---

fluentd/Dockerfile

This PR:
* Changes the runtime image to ubi-minimal
* Removed development dependencies from runtime image
* https://issues.redhat.com/browse/LOG-4455

LOG-4455: remove devel tools from final image and use ubi minimal

---

fluentd/Gemfile
fluentd/Gemfile.lock

This PR removes obsolete gems to resolve CVE
* https://issues.redhat.com/browse/LOG-4428

LOG-4428: removed obsolete gems to resolve CVE

---

fluentd/Dockerfile
fluentd/Dockerfile.in
fluentd/log4366_ruby_lib_net_http.patch

This PR:
* modifies ruby net/http.rb HTTP#start to check the env no proxy vars
* prefers NO_PROXY over no_proxy
* https://issues.redhat.com/browse/LOG-4366
* related to #100

LOG-4366: fix ruby net/http.rb to honor no_proxy in start method

---

fluentd/Gemfile.lock

This PR update `ActiveSupport` gem from `7.0.6` to `7.0.8` to fix vulnerability `CVE-2023-38037: Possible File Disclosure of Locally Encrypted Files`
More info see here: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/activesupport/CVE-2023-38037.yml
/cc 
/cherry-pick 
- Bugzilla:
- JIRA: https://issues.redhat.com/browse/LOG-4489

LOG-4489: update ActiveSupport gem from 7.0.6 to 7.0.8 to fix vulnerability CVE-2023-38037 

---

fluentd/fluent-plugin-elasticsearch.source0001.patch

This PR fixes support for host/hosts placeholders specifically for ipv6 addresses.
Before this fix, IPv6 addresses would not be parsed correctly after evaluating host/hosts for placeholders.
Upstream PR is here : https://github.com/uken/fluent-plugin-elasticsearch/pull/1030
/cc @cahartma @syedriko 
- JIRA: https://issues.redhat.com/browse/LOG-4281

LOG-4281: Fluentd is unable to forward logs to external ipv6 elasticsearch instance

---

fluentd/Dockerfile
fluentd/fluent-plugin-elasticsearch.source0001.patch

This is a forward port of https://github.com/ViaQ/logging-fluentd/pull/105.
This PR fixes support for host/hosts placeholders specifically for ipv6 addresses.
Before this fix, IPv6 addresses would not be parsed correctly after evaluating host/hosts for placeholders.
/cc @cahartma 
- JIRA: https://issues.redhat.com/browse/LOG-4811

LOG-4811: Fluentd is unable to forward logs to external ipv6 elasticsearch instance

---

fluentd/Gemfile
fluentd/Gemfile.lock

This PR:
* Updates openssl to 3.2.0 as advised by RHEL team to support reading private key on FIPS enabled cluster
* https://issues.redhat.com/browse/LOG-3933

LOG-3933: Upgrade openssl gem to v3.2.0 to read private key in FIPS mode
